### ISSUE TITLE
Support for Python 3.12 and drop Python 3.8

### ISSUE THREAD

**Issue by RobPasMue** [ansys/ansys-tools-path#171]
@koubaa @germa89 @nmalsang 

According to [ADR-21](https://adrs.ansys.com/docs/adrs/0021-python-version-support/), this package should be supporting at least Python 3.12 actively (i.e. building the wheelhouse). Also, lowest supported Python version should be 3.9 - Python 3.8 is close to EOL and its support is not recommended anymore.

**Comment by greschd** [comment]
I think adding support for 3.12 is the more important bit here.

**Comment by koubaa** [comment]
@Gryfenfer97 could you please add 3.12 support and patch the release?

**Comment by Gryfenfer97** [comment]
> @Gryfenfer97 could you please add 3.12 support and patch the release?

The tests already pass with python 3.12, the only edit I can see is to add a line in the [pyproject.toml](https://github.com/ansys/ansys-tools-path/blob/main/pyproject.toml#L21C1-L21C46) to specify in the pypi page that we support python 3.12

**Comment by RobPasMue** [comment]
https://github.com/ansys/ansys-tools-path/blob/fe6571262916d0861885eb95e207bbde0eda526f/.github/workflows/ci_cd.yml#L31

We are not performing wheelhouses or smoke tests with 3.12

Plus, as you mention, the metadata in the pyproject.toml file should be updated accordingly
