### ISSUE TITLE
Add method to get the latest available Ansys installation

### ISSUE THREAD

**Issue by greschd** [ansys/ansys-tools-path#38]
### 📝 Description of the feature

It would be useful to have a method that returns the location of the latest installed Ansys. Since ``get_available_ansys_installations`` can return both normal and Student installs, I would propose the following logic:
- Always use the latest available release
- If there is both a student and regular install for the latest release, use the regular install.

Use case: for providing a useful default when configuring how a product is launched.

### 💡 Steps for implementing the feature

Example implementation:

```python
def get_latest_ansys_installation():
    installations = get_available_ansys_installations()
    if not installations:
         raise ValueError("No Ansys installation found.")

    def sort_key(version_nr):
        if version_nr < 0:
            return abs(version_nr) - 0.5
        return version_nr

    latest_key = max(installations, key=sort_key)
    return installations[latest_key]
```

**Comment by germa89** [comment]
This seems a good idea. Assigning to @Gryfenfer97
