### ISSUE TITLE
atp.get_mechanical_path(version=222, allow_input=True) throws an error

### ISSUE THREAD

**Issue by koubaa** [ansys/ansys-tools-path#52]
I am using this API interactively in order to set the path, and I get an error:
ValueError: Version 222 not found. Available versions are [232]

**Comment by germa89** [comment]
We are having issues to reproduce it. Can you post the code and the traceback?

Stupid suggestions, maybe you don't have 222 installed? @Gryfenfer97

**Comment by Gryfenfer97** [comment]
I am able to reproduce it using the tests with pyfakefs but only on windows

**Comment by Gryfenfer97** [comment]
Can you send us all your environment variable that start with a `AWP_ROOT` ?
```ps
gci env:* | grep AWP_ROOT
```
in powershell

**Comment by koubaa** [comment]
AWP_ROOT232='C:\AnsysDev\NoBackup\Program Files\ANSYS Inc\v232'
AWP_ROOT241='C:\AnsysDev\NoBackup\Program Files\ANSYS Inc\v241'

**Comment by koubaa** [comment]
@Gryfenfer97 I agree and disagree. The missing environment variable is indeed why ansys_tools_path cannot find the installed version.

The bug here is, specifically that:

- `allow_input=True` is supposed to let the user specify where to find the installation if it is not found. So any time allow_input is true, there should not be an error, and the user can point to a folder where they say the installation is in.

**Comment by koubaa** [comment]
@Gryfenfer97 ah - it should register it in the config file.  This is more common on linux, where the AWP_ROOT env vars are not set by the installer. (but it's possible on windows too, some developers install multiple builds of the same version workbench and unset the env var globally)

**Comment by Gryfenfer97** [comment]
So I guess we can change the function `get_mechanical_path`
to something like:

```python
def get_mechanical(version=None, allow_input=True):
    return _get_application_path("mechanical", allow_input, version)

def _get_application_path(
    product: PRODUCT_TYPE, allow_input: bool = True, version: Optional[float] = None
):
    exe_loc, exe_version = _find_installation(product, version)
    if (exe_loc, exe_version) != ("", ""): # executable not found
        if os.path.isfile(exe_loc):
            return exe_loc

    if allow_input:
        exe_loc = _prompt_path(product)
        _change_default_path(product, exe_loc) # this write in the config file
        return exe_loc

    return None
```

**Comment by koubaa** [comment]
@Gryfenfer97 yes, I think that matches more the intent, thanks!
