### ISSUE TITLE
Migration broken on development version

### ISSUE THREAD

**Issue by koubaa** [ansys/ansys-tools-path#54]
See my comments on #44 

Any other issues that need to be fixed need to be put into patch releases until this is fixed

**Comment by koubaa** [comment]
@Gryfenfer97 now that this issue is fixed, could you please publish a new release to pypi?

**Comment by Gryfenfer97** [comment]
I just have one more thing to add. To specify to type checker that our library is typed, we need to add a file called py.typed to the library, I just need to figure where exactly I need to put it
