### ISSUE TITLE
remove support for python 3.7

### ISSUE THREAD

**Issue by Gryfenfer97** [ansys/ansys-tools-path#71]
### 📝 Description of the feature

As pymechanical and pymapdl have dropped their support for python 3.7 (respectively on May 3 and June 14) we should drop it too

### 💡 Steps for implementing the feature

- [ ] Update pyproject.toml
- [ ] Remove python 3.7 tests from CI

**Comment by RobPasMue** [comment]
Not only PyMAPDL and PyMechanical... but all PyAnsys libraries. The metapackage dropped it support some months ago 😄 Thanks for opening this @Gryfenfer97 !
